apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 1337
  selector:
    app: api
  sessionAffinity: None
  type: ClusterIP